# Generated by Django 4.2.2 on 2023-06-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_dni', models.IntegerField(max_length=10)),
                ('name', models.TextField(max_length=200, null=True)),
                ('surname', models.TextField(max_length=200, null=True)),
                ('gender', models.TextField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('requested_amount', models.IntegerField(null=True)),
            ],
        ),
    ]
