# Generated by Django 4.2.2 on 2023-06-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='number_dni',
            field=models.IntegerField(),
        ),
    ]
